[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]

linker = "flip-link"
rustflags = [
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "no-vectorize-loops",
]

runner = "probe-rs run --chip RP2040 --protocol swd"


[env]
DEFMT_LOG = "info"
CC_thumbv6m_none_eabi = "C:/Users/ts286220/Documents/FACS Temp/arm-gnu-toolchain-15.2.rel1-mingw-w64-i686-arm-none-eabi/bin/arm-none-eabi-gcc.exe"
AR_thumbv6m_none_eabi = "C:/Users/ts286220/Documents/FACS Temp/arm-gnu-toolchain-15.2.rel1-mingw-w64-i686-arm-none-eabi/bin/arm-none-eabi-ar.exe"

# Tell 'bindgen' (Clang) where the standard ARM C headers (like stdint.h) live
BINDGEN_EXTRA_CLANG_ARGS = "--sysroot=C:/Users/ts286220/Documents/FACS Temp/arm-gnu-toolchain-15.2.rel1-mingw-w64-i686-arm-none-eabi/arm-none-eabi"
